CREATE TABLE public.entities_offerings (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  euid UUID NULL,
  name text NULL,
  description text NULL,
  url text NULL,
  images jsonb NULL,
  type text NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  CONSTRAINT entities_offerings_pkey PRIMARY KEY (id),
  CONSTRAINT entities_offerings_euid_fkey FOREIGN key (euid) REFERENCES entities (euid) ON DELETE cascade
) tablespace pg_default;

ALTER TABLE "entities_offerings" ENABLE ROW LEVEL SECURITY;

-- TODO: This will need to be changed at some point, enable accurate
-- policies.
CREATE POLICY "Enable all actions for authenticated users only" ON "entities_offerings" AS PERMISSIVE FOR INSERT TO authenticated
WITH
  CHECK (TRUE);

