CREATE TABLE public.insights (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  euid UUID NULL,
  platform text NULL,
  type text NULL,
  data jsonb NULL,
  auid UUID NULL,
  CONSTRAINT insights_pkey PRIMARY KEY (id),
  CONSTRAINT insights_euid_fkey FOREIGN key (euid) REFERENCES entities (euid) ON UPDATE cascade ON DELETE SET NULL
) tablespace pg_default;

ALTER TABLE "job_scheduler" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Full Access" ON "public"."insights" AS PERMISSIVE FOR ALL TO anon,
authenticated

