CREATE TABLE public.job_scheduler (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NULL,
  description text NULL,
  status text NULL,
  type text NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  CONSTRAINT job_scheduler_pkey PRIMARY KEY (id)
) tablespace pg_default;

ALTER TABLE "job_scheduler" ENABLE ROW LEVEL SECURITY;

